export const HERO_GLASS_CONFIG = {
  ior: {
    red: 1.15,
    yellow: 1.16,
    green: 1.18,
    cyan: 1.22,
    blue: 1.22,
    purple: 1.22,
  },
  refractPower: 0.72,
  chromaticAberration: 0.14,
  loopCount: 3,
  specularStrength: 1.2,
  lightZ: 0.5,
  dark: {
    shininess: 100,
    diffuseness: 0.05,
    fresnelPower: 3,
    fresnelStrength: 0.72,
    brightness: 0.6,
    contrast: 0.98,
    gamma: 1,
    saturation: 1.2,
    tintColorA: "#f4f4f0",
    tintColorB: "#dde8ff",
    tintMinimumAlpha: 1,
    tintMaximumAlpha: 0.4,
  },
  light: {
    shininess: 120,
    diffuseness: 0.1,
    fresnelPower: 1,
    fresnelStrength: 0.24,
    brightness: 0.78,
    contrast: 0.9,
    gamma: 1,
    saturation: 1.2,
    tintColorA: "#22d6d6",
    tintColorB: "#a855f7",
    tintMinimumAlpha: 1,
    tintMaximumAlpha: 0.92,
  },
  tintMix: 1,
  fresnelSideDirection: [-1, 1, -1],
  renderLayer: 10,
  resolutionScale: 0.5,
} as const;
